name: Publish Release
on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    env:
      SOLUTION: 'src/Hawf.sln'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Setup Dependencies
        run: nuget restore $SOLUTION
      
      - name: Configure .NET 6
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: Build Solution
        run: dotnet build $SOLUTION --configuration Release -p:Version=${{ env.RELEASE_VERSION }} --no-restore
        
      - name: Run Tests
        run: dotnet test /p:Configuration=Release --no-restore --no-build --verbosity normal
      
      - name: ZIP Artifacts
        uses: papeloto/action-zip@v1
        with:
            files: ./
            dest: package.zip
        
      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        with:
          name: build
          path: ${{ github.workspace }}/package.zip
      
      - name: NuGet Publish
        run: dotnet nuget push "**/*.nupkg" --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json
